[build]
  command = "bundle install && bundle exec jekyll build"
  functions = "netlify/functions"
  publish = "_site"

[build.environment]
  MISE_RUBY_COMPILE = "false"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "bundle exec jekyll serve --port 4003"
  targetPort = 4003
  port = 8888
  publish = "_site"
  autoLaunch = false
