[build]
  command = "bundle install && bundle exec jekyll build"
  functions = "netlify/functions"
  publish = "_site"

[build.environment]
  MISE_RUBY_COMPILE = "false"

[functions]
  node_bundler = "esbuild"

[dev]
  targetPort = 4003
